### ISSUE TITLE
Tarefas

### ISSUE THREAD

**Issue by kelvinoenning** [kelvinoenning/hugo-theme-minimalist#1]
# Regras
1. Cada tarefa deve possuir sua própria Issue para controle da tarefa e discussão de design ou algo relacionado.
2. A issue deve ser adicionada na listagem da versão.
3. Após iniciar os trabalhos de uma versão, novas tarefas não podem ser adicionadas.
4. Qualquer `correção/melhorias` necessária deve ser adicionada na lista de `correções/melhorias` da versão junto da Issue.
5. Melhorias somente são aceitas quando não mudam o foco descrito da tarefa.
---

# V 1.1.0
1. Compartilhamento
   - [x] #38 Adicionar compartilhamento com **Facebook**.
   - [x] #39 Adicionar compartilhamento com **Twitter**.
2. Comentários
   - [x] #40 Adicionar sistema comentários com **disqus**.
3. Google
   - [x] #41 Adicionar **Google Analytics**.

#### Lista de melhorias

- [ ] #50 Deixar todos os parâmetros de configuração em caixa baixa

#### Lista de correções

- [x] #48  Bug na separação das listas no Markdown.
- [x] #49 Tabelas não estão renderizando no Markdown.

---
# V 1.0.1
1. Código inicial
   - [x] #2 Gerar o código simplificado do tema.
   - [x] #3 Importar *reset CSS*.
   - [x] #4 Importar ícones *SVG*.
2. Barra de menu.
   - [x] #5 Adicionar um menu simplificado com o título do blog centralizado.
   - [x] #6 Adicionar a logo na esquerda do título (caso configurado).
   - [x] #7 Adicionar a lista de links (caso configurado).
3. Lista de posts
   - [x] #8 Adicionar a lista de posts na página inicial.
4. Página do post
   - [x] #9 Construção da página para a apresentação do post.
   - [x] #10 Importar um estilo para o *highlight* dos blocos de códigos publicados no post.
5. Adição do SEO
   - [x] #11 Adicionar a configuração de SEO na página inicial
   - [x] #12 Adicionar a configuração de SEO na página do post

#### Lista de melhorias

- [x] #23 Criar uma partial para fazer a importação dos arquivos CSS.
- [x] #24 Criar uma partial para fazer a importação dos arquivos JS.
- [x] #26 Possibilitar aos mobiles o retorno da página com um botão fixo no canto inferior direito.
- [x] #28 Ajustar as fontes.
- [x] #36 Melhorar a separação do textos dos cards de posts.

#### Lista de correções

- [x] #25 Bug com o espaçamento do container.
- [x] #27 Mudar a variável do título do blog.
